### ISSUE TITLE
Time accrued not registered if computer is powered down, without locking it

### ISSUE THREAD

**Issue by EddyStacks** [Moustachauve/Timesheet-Hero#10]
Steps:

1. Open computer.
2. Launch Timesheet Hero application.
3. Wait an hour or two, to accumulate time.
4. Power down the computer.
5. Turn on the computer.
6. Launch Timesheet Hero application.
7. Observe registered time.

Result: Time is not registered when computer is turned off.

Expected: Time accrued should not be limited to locking the computer.

**Comment by Moustachauve** [comment]
This will be fixed in version v1.5.2 . I changed it so a locked event will happen when the app is closed and/or forced to be shutdown because of a windows shutdown/restart/...
