### ISSUE TITLE
going back to current workweek

### ISSUE THREAD

**Issue by sandrodago** [Moustachauve/Timesheet-Hero#7]
If I look back to last week's work hours, I cannot go forward and get back to current week. If I want to set the current week in the settings, It won't let me chose the current day. When I close the window and reopen, it still doesn't give me current week. I need to end the process and then restart the application for it to refresh back to my current work week.

**Comment by Moustachauve** [comment]
This was fixed in a recent commit. It will be deployed in the next version 1.5.0
